-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cities
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.companies
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(250) NOT NULL,
    owner character varying(100) NOT NULL,
    email character varying(35) NOT NULL,
    city_id integer NOT NULL,
    district_id integer NOT NULL,
    phone_number character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    mobile character varying(15) NOT NULL,
    email character varying(50) NOT NULL,
    city_id integer NOT NULL,
    company_id integer NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.districts
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_id integer NOT NULL,
    name character varying(35) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estate_typies
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estates
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_id integer NOT NULL,
    district_id integer NOT NULL,
    estate_type_id integer NOT NULL,
    size integer NOT NULL,
    room character varying(3) NOT NULL,
    flat integer NOT NULL,
    type_of_heating character varying NOT NULL,
    price real NOT NULL,
    customer_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.companies
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.companies
    ADD FOREIGN KEY (district_id)
    REFERENCES public.districts (id)
    NOT VALID;


ALTER TABLE public.customers
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.customers
    ADD FOREIGN KEY (company_id)
    REFERENCES public.companies (id)
    NOT VALID;


ALTER TABLE public.districts
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.estates
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.estates
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (id)
    NOT VALID;


ALTER TABLE public.estates
    ADD FOREIGN KEY (district_id)
    REFERENCES public.districts (id)
    NOT VALID;


ALTER TABLE public.estates
    ADD FOREIGN KEY (estate_type_id)
    REFERENCES public.estate_typies (id)
    NOT VALID;

END;